{
 "title": "Tempest",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "LOC",
    "label": "Loc",
    "query": "SHOW TAG VALUES FROM \"statushub\" WITH KEY = \"Loc\""
   }
  ]
 },
 "panels": [
  { "title": "Cockpit $LOC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "LOC" },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "AirTemperatureC" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "RelativeHumidityPct" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "Station pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "StationPressureMB" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind (Gust)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "WindGustMPS" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*3.6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind (avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "WindAvgMPS" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*3.6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "Brightness",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "IlluminanceLux" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "UVIndex" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "Global radiation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "SolarRadiationWPSQM" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "Last rain start",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "time:YY-MM-DD hh:mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "lightningstrike",
     "query": "SELECT last(*) FROM \"rainstart\" WHERE (\"Loc\"::tag =~ /^$LOC$/)",
     "select": [
      [
       { "params": [ "time" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rain 1h",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "RainAmountOverPreviousMinuteMM" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "Rain 24h",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "RainAmountOverPreviousMinuteMM" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  { "title": "Dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$LOC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Loc::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "AirTemperatureC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "$LOC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "RelativeHumidityPct" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "Station pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "alias": "$LOC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "StationPressureMB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "alias": "$LOC $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "WindAvgMPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*3.6" ], "type": "math" },
       { "params": [ "avg" ], "type": "alias" }
      ],
      [
       { "params": [ "WindGustMPS" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*3.6" ], "type": "math" },
       { "params": [ "gust" ], "type": "alias" }
      ],
      [
       { "params": [ "WindLullMPS" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "*3.6" ], "type": "math" },
       { "params": [ "lull" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "Brightness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "alias": "$LOC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "IlluminanceLux" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$LOC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "UVIndex" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "Rain amount per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "alias": "$LOC",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "RainAmountOverPreviousMinuteMM" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "Global radiation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "alias": "$LOC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "SolarRadiationWPSQM" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "Rain amount per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "alias": "$LOC",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "RainAmountOverPreviousMinuteMM" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "Lightning strikes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$LOC",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "LightningStrikeCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "Lightning Strikes",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "alias": "distance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lightningstrike",
     "select": [
      [
       { "params": [ "DistanceKM" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "$LOC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "observation",
     "select": [
      [
       { "params": [ "BatteryV" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "$LOC hub rssi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "statushub",
     "select": [
      [
       { "params": [ "RSSI" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    },
    {
     "alias": "$LOC $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "statusdevice",
     "select": [
      [
       { "params": [ "HubRSSI" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "device hub rssi" ], "type": "alias" }
      ],
      [
       { "params": [ "RSSI" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "device rssi" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Loc::tag", "operator": "=~", "value": "/^$LOC$/" }
     ]
    }
   ]
  }
 ]
}